// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icpusakvwpwcgvdffsvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcHVzYWt2d3B3Y2d2ZGZmc3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTEzMDksImV4cCI6MjA2NjM2NzMwOX0.BPx6ByZDOd1bP5zHO5sfnN2uquoumR-e97H5WCyqKrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);